[[redirects]]
from = "http:*"
to = "https://:splat"
status = 301
force = true



[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'self'; img-src 'self' https:; script-src 'self' https:; style-src 'self' https:;"
