import img_1 from "./assets/profile-image/img-1.jpg";
import img_2 from "./assets/profile-image/img-2.webp";
import img_3 from "./assets/profile-image/img-3.webp";
import img_4 from "./assets/profile-image/img-4.jpg";
import img_5 from "./assets/profile-image/img-5.avif";
import img_6 from "./assets/profile-image/img-6.jpg";
import img_7 from "./assets/profile-image/img-7.webp";
import img_8 from "./assets/profile-image/img-6.jpg";
import img_9 from "./assets/profile-image/img-9.jpeg";
import img_10 from "./assets/profile-image/img-10.jpg";

export const user_data = [
    {
        id: 1,
        name: "Leanne Graham",
        username: "Bret",
        email: "Sincere@april.biz",
        phone: "1-770-736-8031 x56442",
        image: img_1,
        designation: "Frontend Developer",
        social: {
            post: 100,
            followers: "1k",
            followings: "3k",
        },
        socialHandle: {
            link_insta: "https://www.instagram.com/ismail_15_/",
            link_facebook: "https://www.facebook.com/",
            link_github: "https://github.com/md-ismaeel",
            link_linkedin: "https://www.linkedin.com/in/md-ismaeel/",
            link_twitter: "https://x.com/impossible_br03",
        },
    },
    {
        id: 2,
        name: "Ervin Howell",
        username: "Antonette",
        email: "Shanna@melissa.tv",
        phone: "010-692-6593 x09125",
        image: img_2,
        designation: "FullStack Developer",
        social: {
            post: 75,
            followers: "4k",
            followings: "10k",
        },
        socialHandle: {
            link_insta: "https://www.instagram.com/ismail_15_/",
            link_facebook: "https://www.facebook.com/",
            link_github: "https://github.com/md-ismaeel",
            link_linkedin: "https://www.linkedin.com/in/md-ismaeel/",
            link_twitter: "https://x.com/impossible_br03",
        },
    },
    {
        id: 3,
        name: "Clementine Bauch",
        username: "Samantha",
        email: "Nathan@yesenia.net",
        phone: "1-463-123-4447",
        image: img_3,
        designation: "Ui/Ux Designer",
        social: {
            post: 150,
            followers: "4k",
            followings: "80k",
        },
        socialHandle: {
            link_insta: "https://www.instagram.com/ismail_15_/",
            link_facebook: "https://www.facebook.com/",
            link_github: "https://github.com/md-ismaeel",
            link_linkedin: "https://www.linkedin.com/in/md-ismaeel/",
            link_twitter: "https://x.com/impossible_br03",
        },
    },
    {
        id: 4,
        name: "Patricia Lebsack",
        username: "Karianne",
        email: "Julianne.OConner@kory.org",
        phone: "493-170-9623 x156",
        image: img_4,
        designation: "Frontend Developer",
        social: {
            post: 300,
            followers: "100k",
            followings: "200",
        },
        socialHandle: {
            link_insta: "https://www.instagram.com/ismail_15_/",
            link_facebook: "https://www.facebook.com/",
            link_github: "https://github.com/md-ismaeel",
            link_linkedin: "https://www.linkedin.com/in/md-ismaeel/",
            link_twitter: "https://x.com/impossible_br03",
        },
    },
    {
        id: 5,
        name: "Chelsey Dietrich",
        username: "Kamren",
        email: "Lucio_Hettinger@annie.ca",
        phone: "(254)954-1289",
        image: img_5,
        designation: "Backend developer",
        social: {
            post: 300,
            followers: "150k",
            followings: "499",
        },
        socialHandle: {
            link_insta: "https://www.instagram.com/ismail_15_/",
            link_facebook: "https://www.facebook.com/",
            link_github: "https://github.com/md-ismaeel",
            link_linkedin: "https://www.linkedin.com/in/md-ismaeel/",
            link_twitter: "https://x.com/impossible_br03",
        },
    },
    {
        id: 6,
        name: "Mrs. Dennis Schulist",
        username: "Leopoldo_Corkery",
        email: "Karley_Dach@jasper.info",
        phone: "1-477-935-8478 x6430",
        image: img_6,
        designation: "Java developer",
        social: {
            post: 299,
            followers: "200k",
            followings: "1000",
        },
        socialHandle: {
            link_insta: "https://www.instagram.com/ismail_15_/",
            link_facebook: "https://www.facebook.com/",
            link_github: "https://github.com/md-ismaeel",
            link_linkedin: "https://www.linkedin.com/in/md-ismaeel/",
            link_twitter: "https://x.com/impossible_br03",
        },
    },
    {
        id: 7,
        name: "Kurtis Weissnat",
        username: "Elwyn.Skiles",
        email: "Telly.Hoeger@billy.biz",
        phone: "210.067.6132",
        image: img_7,
        designation: "FullStack Developer",
        social: {
            post: 400,
            followers: "500k",
            followings: "900",
        },
        socialHandle: {
            link_insta: "https://www.instagram.com/ismail_15_/",
            link_facebook: "https://www.facebook.com/",
            link_github: "https://github.com/md-ismaeel",
            link_linkedin: "https://www.linkedin.com/in/md-ismaeel/",
            link_twitter: "https://x.com/impossible_br03",
        },
    },
    {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        username: "Maxime_Nienow",
        email: "Sherwood@rosamond.me",
        phone: "586.493.6943 x140",
        image: img_8,
        designation: "Mearn Stack Developer",
        social: {
            post: "1000",
            followers: "1M",
            followings: "1200",
        },
        socialHandle: {
            link_insta: "https://www.instagram.com/ismail_15_/",
            link_facebook: "https://www.facebook.com/",
            link_github: "https://github.com/md-ismaeel",
            link_linkedin: "https://www.linkedin.com/in/md-ismaeel/",
            link_twitter: "https://x.com/impossible_br03",
        },
    },
    {
        id: 9,
        name: "Glenna Reichert",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        phone: "(775)976-6794 x41206",
        image: img_9,
        designation: "Ui/Ux Designer",
        social: {
            post: "500",
            followers: "200k",
            followings: "700",
        },
        socialHandle: {
            link_insta: "https://www.instagram.com/ismail_15_/",
            link_facebook: "https://www.facebook.com/",
            link_github: "https://github.com/md-ismaeel",
            link_linkedin: "https://www.linkedin.com/in/md-ismaeel/",
            link_twitter: "https://x.com/impossible_br03",
        },
    },
    {
        id: 10,
        name: "Clementina DuBuque",
        username: "Moriah.Stanton",
        email: "Rey.Padberg@karina.biz",
        phone: "024-648-3804",
        image: img_10,
        designation: ".Net Developer",
        social: {
            post: "345",
            followers: "500k",
            followings: "1k",
        },
        socialHandle: {
            link_insta: "https://www.instagram.com/ismail_15_/",
            link_facebook: "https://www.facebook.com/",
            link_github: "https://github.com/md-ismaeel",
            link_linkedin: "https://www.linkedin.com/in/md-ismaeel/",
            link_twitter: "https://x.com/impossible_br03",
        },
    },
];
