import img from "./assets/Product-images/organic.png";

export const PRODUCTS = [
    // Dairy Products
    {
        id: 1,
        name: "Fresh Cow Milk",
        category: "Dairy",
        price: 50,
        description: "Pure, farm-fresh cow milk delivered daily",
        image: img,
        brand: "GreenPastures",
        type: "Whole Milk",
        weight: "1 Liter",
        discount: 10,
    },
    {
        id: 2,
        name: "Organic Ghee",
        category: "Dairy",
        price: 300,
        description: "Traditional handmade ghee from grass-fed cows",
        image: img,
        brand: "NaturalHeritage",
        type: "A2 Cow Ghee",
        weight: "500g",
        discount: 15,
    },
    {
        id: 3,
        name: "Homemade Paneer",
        category: "Dairy",
        price: 150,
        description: "Soft, fresh paneer made from pure milk",
        image: img,
        brand: "FarmFresh",
        type: "Classic Paneer",
        weight: "250g",
        discount: 5,
    },
    {
        id: 4,
        name: "Curd (Yogurt)",
        category: "Dairy",
        price: 40,
        description: "Creamy, probiotic-rich traditional curd",
        image: img,
        brand: "ProBio",
        type: "Regular Curd",
        weight: "500ml",
        discount: 8,
    },
    {
        id: 5,
        name: "Buttermilk",
        category: "Dairy",
        price: 30,
        description: "Refreshing, naturally churned buttermilk",
        image: img,
        brand: "CreamyDelights",
        type: "Traditional Buttermilk",
        weight: "250ml",
        discount: 12,
    },
    {
        id: 6,
        name: "Organic Tomatoes",
        category: "Vegetables",
        price: 40,
        description: "Farm-fresh, naturally grown tomatoes",
        image: img,
        brand: "OrganicHarvest",
        type: "Vine Tomatoes",
        weight: "1 kg",
        discount: 15,
    },
    {
        id: 7,
        name: "Green Spinach Bunch",
        category: "Vegetables",
        price: 25,
        description: "Nutrient-rich, locally grown spinach",
        image: img,
        brand: "GreenFields",
        type: "Baby Spinach",
        weight: "250g",
        discount: 5,
    },
    {
        id: 8,
        name: "Organic Cucumber",
        category: "Vegetables",
        price: 30,
        description: "Fresh, crisp cucumbers from our farm",
        image: img,
        brand: "FreshHarvest",
        type: "English Cucumber",
        weight: "500g",
        discount: 10,
    },
    {
        id: 9,
        name: "Farm Fresh Carrots",
        category: "Vegetables",
        price: 35,
        description: "Sweet and crunchy organic carrots",
        image: img,
        brand: "RootRanch",
        type: "Orange Carrots",
        weight: "1 kg",
        discount: 12,
    },
    {
        id: 10,
        name: "Green Capsicum",
        category: "Vegetables",
        price: 40,
        description: "Crisp and flavorful capsicum",
        image: img,
        brand: "VeggiePro",
        type: "Bell Pepper",
        weight: "500g",
        discount: 8,
    },
    {
        id: 11,
        name: "Organic Bananas",
        category: "Fruits",
        price: 50,
        description: "Ripe, sweet bananas from our organic farm",
        image: img,
        brand: "TropicalHarvest",
        type: "Cavendish Bananas",
        weight: "1 kg",
        discount: 10,
    },
    {
        id: 12,
        name: "Fresh Mangoes",
        category: "Fruits",
        price: 100,
        description: "Juicy, sun-ripened mangoes",
        image: img,
        brand: "SunRipe",
        type: "Alphonso Mangoes",
        weight: "1 kg",
        discount: 15,
    },
    {
        id: 13,
        name: "Organic Apples",
        category: "Fruits",
        price: 80,
        description: "Crisp and sweet organic apples",
        image: img,
        brand: "OrchardGold",
        type: "Red Delicious",
        weight: "1 kg",
        discount: 12,
    },
    {
        id: 14,
        name: "Papaya",
        category: "Fruits",
        price: 60,
        description: "Fresh, ripe papayas full of nutrition",
        image: img,
        brand: "TropicalTreat",
        type: "Hawaiian Papaya",
        weight: "1 kg",
        discount: 8,
    },
    {
        id: 15,
        name: "Organic Pomegranate",
        category: "Fruits",
        price: 120,
        description: "Nutrient-rich, freshly harvested pomegranates",
        image: img,
        brand: "FruitMaster",
        type: "Ruby Red Pomegranate",
        weight: "1 kg",
        discount: 10,
    },
    {
        id: 16,
        name: "Organic Rice",
        category: "Grains",
        price: 80,
        description: "Locally grown, pesticide-free rice",
        image: img,
        brand: "GrainHaven",
        type: "Basmati Rice",
        weight: "1 kg",
        discount: 12,
    },
    {
        id: 17,
        name: "Whole Wheat Flour",
        category: "Grains",
        price: 50,
        description: "Stone-ground, nutritious wheat flour",
        image: img,
        brand: "MillStone",
        type: "Whole Wheat Atta",
        weight: "1 kg",
        discount: 8,
    },
    {
        id: 18,
        name: "Organic Toor Dal",
        category: "Pulses",
        price: 120,
        description: "Premium quality toor dal, farm-fresh",
        image: img,
        brand: "PulsePro",
        type: "Split Pigeon Peas",
        weight: "1 kg",
        discount: 10,
    },
    {
        id: 19,
        name: "Moong Dal",
        category: "Pulses",
        price: 100,
        description: "Protein-rich, organic moong dal",
        image: img,
        brand: "LegumeLand",
        type: "Split Green Gram",
        weight: "1 kg",
        discount: 12,
    },
    {
        id: 20,
        name: "Red Lentils",
        category: "Pulses",
        price: 90,
        description: "Nutrient-dense, organic red lentils",
        image: img,
        brand: "DalDelights",
        type: "Masoor Dal",
        weight: "1 kg",
        discount: 8,
    },
    {
        id: 21,
        name: "Organic Turmeric Powder",
        category: "Spices",
        price: 60,
        description: "Pure, hand-ground turmeric powder",
        image: img,
        brand: "SpiceMaster",
        type: "Ground Turmeric",
        weight: "100g",
        discount: 10,
    },
    {
        id: 22,
        name: "Organic Red Chili Powder",
        category: "Spices",
        price: 70,
        description: "Freshly ground, aromatic red chili powder",
        image: img,
        brand: "FireSpice",
        type: "Kashmiri Red Chili",
        weight: "100g",
        discount: 12,
    },
    {
        id: 23,
        name: "Garam Masala",
        category: "Spices",
        price: 80,
        description: "Traditional blend of aromatic spices",
        image: img,
        brand: "AromaKit",
        type: "Classic Garam Masala",
        weight: "100g",
        discount: 15,
    },
    {
        id: 24,
        name: "Cold-Pressed Mustard Oil",
        category: "Cooking Oils",
        price: 150,
        description: "Pure, unrefined mustard oil",
        image: img,
        brand: "OilCraft",
        type: "Kachi Ghani Mustard Oil",
        weight: "1 Liter",
        discount: 10,
    },
    {
        id: 25,
        name: "Coconut Oil",
        category: "Cooking Oils",
        price: 200,
        description: "Virgin, cold-pressed coconut oil",
        image: img,
        brand: "TropicalPress",
        type: "Extra Virgin Coconut Oil",
        weight: "500ml",
        discount: 15,
    },
    {
        id: 26,
        name: "Organic Honey",
        category: "Farm Products",
        price: 250,
        description: "Pure, raw honey from our beehives",
        image: img,
        brand: "NectarPure",
        type: "Wild Forest Honey",
        weight: "500g",
        discount: 12,
    },
    {
        id: 27,
        name: "Farm Fresh Eggs",
        category: "Farm Products",
        price: 60,
        description: "Free-range, organic chicken eggs",
        image: img,
        brand: "HappyHens",
        type: "Large White Eggs",
        weight: "1 Dozen",
        discount: 8,
    },
    {
        id: 28,
        name: "Organic Jaggery",
        category: "Farm Products",
        price: 100,
        description: "Traditional, unrefined cane jaggery",
        image: img,
        brand: "SweetNatural",
        type: "Whole Cane Jaggery",
        weight: "500g",
        discount: 10,
    },
    {
        id: 29,
        name: "Fresh Green Chili",
        category: "Vegetables",
        price: 20,
        description: "Spicy, farm-fresh green chilies",
        image: img,
        brand: "SpiceFarm",
        type: "Hybrid Green Chilies",
        weight: "250g",
        discount: 5,
    },
    {
        id: 30,
        name: "Organic Onions",
        category: "Vegetables",
        price: 40,
        description: "Fresh, locally grown organic onions",
        image: img,
        brand: "RootMaster",
        type: "Red Onions",
        weight: "1 kg",
        discount: 8,
    },
    {
        id: 31,
        name: "Fresh Coriander Leaves",
        category: "Herbs",
        price: 15,
        description: "Aromatic, fresh coriander bunch",
        image: img,
        brand: "HerbHarvest",
        type: "Organic Coriander",
        weight: "100g",
        discount: 10,
    },
    {
        id: 32,
        name: "Mint Leaves",
        category: "Herbs",
        price: 20,
        description: "Fresh, fragrant mint leaves",
        image: img,
        brand: "LeafyFresh",
        type: "Garden Mint",
        weight: "100g",
        discount: 12,
    },
    {
        id: 33,
        name: "Curry Leaves",
        category: "Herbs",
        price: 15,
        description: "Freshly picked curry leaves",
        image: img,
        brand: "AromaGreen",
        type: "Fresh Curry Leaves",
        weight: "50g",
        discount: 8,
    },
    {
        id: 34,
        name: "Ginger",
        category: "Herbs",
        price: 40,
        description: "Fresh, organic ginger root",
        image: img,
        brand: "RootSpice",
        type: "Organic Ginger",
        weight: "250g",
        discount: 10,
    },
    {
        id: 35,
        name: "Garlic",
        category: "Herbs",
        price: 50,
        description: "Fresh, organic garlic bulbs",
        image: img,
        brand: "AllianceFarms",
        type: "White Garlic",
        weight: "250g",
        discount: 12,
    },
    {
        id: 36,
        name: "A2 Cow Milk",
        category: "Dairy",
        price: 70,
        description: "Pure A2 milk from indigenous cow breeds",
        image: img,
        brand: "PureOmega",
        type: "A2 Jersey Cow Milk",
        weight: "1 Liter",
        discount: 15,
    },
    {
        id: 37,
        name: "Homemade Butter",
        category: "Dairy",
        price: 100,
        description: "Traditional hand-churned butter",
        image: img,
        brand: "CreamCraft",
        type: "Cultured Butter",
        weight: "250g",
        discount: 10,
    },
    {
        id: 38,
        name: "Cottage Cheese",
        category: "Dairy",
        price: 180,
        description: "Fresh, soft cottage cheese",
        image: img,
        brand: "CheeseHub",
        type: "Paneer Style Cottage Cheese",
        weight: "250g",
        discount: 12,
    },
    {
        id: 39,
        name: "Pearl Millet Flour",
        category: "Grains",
        price: 60,
        description: "Organic bajra (pearl millet) flour",
        image: img,
        brand: "MilletMaster",
        type: "Bajra Atta",
        weight: "1 kg",
        discount: 8,
    },

    {
        id: 40,
        name: "Finger Millet Flour",
        category: "Grains",
        price: 70,
        description: "Nutritious ragi (finger millet) flour",
        image: img,
        brand: "NutriGrain",
        type: "Ragi Flour",
        weight: "1 kg",
        discount: 10,
    },
    {
        id: 41,
        name: "Sprouted Moong",
        category: "Pulses",
        price: 50,
        description: "Fresh, organic sprouted moong",
        image: img,
        brand: "SproutWell",
        type: "Green Gram Sprouts",
        weight: "250g",
        discount: 12,
    },
    {
        id: 42,
        name: "Green Peas",
        category: "Vegetables",
        price: 40,
        description: "Farm-fresh, sweet green peas",
        image: img,
        brand: "FreshFields",
        type: "Sweet Green Peas",
        weight: "500g",
        discount: 8,
    },
    {
        id: 43,
        name: "Seasonal Mixed Vegetables",
        category: "Vegetables",
        price: 80,
        description: "Assorted fresh vegetables of the season",
        image: img,
        brand: "HarvestMix",
        type: "Seasonal Vegetable Blend",
        weight: "1 kg",
        discount: 15,
    },
    {
        id: 44,
        name: "Dried Curry Powder",
        category: "Spices",
        price: 90,
        description: "Homemade, aromatic curry powder blend",
        image: img,
        brand: "SpiceSaga",
        type: "Traditional Curry Powder",
        weight: "100g",
        discount: 10,
    },
    {
        id: 45,
        name: "Black Pepper Powder",
        category: "Spices",
        price: 100,
        description: "Freshly ground, premium black pepper",
        image: img,
        brand: "PepperKing",
        type: "Tellicherry Black Pepper",
        weight: "100g",
        discount: 12,
    },
    {
        id: 46,
        name: "Groundnut Oil",
        category: "Cooking Oils",
        price: 180,
        description: "Cold-pressed, pure groundnut oil",
        image: img,
        brand: "OilMaster",
        type: "Groundnut Oil",
        weight: "1 Liter",
        discount: 10,
    },
    {
        id: 47,
        name: "Sunflower Oil",
        category: "Cooking Oils",
        price: 160,
        description: "Refined, healthy sunflower oil",
        image: img,
        brand: "SunnyPress",
        type: "Refined Sunflower Oil",
        weight: "1 Liter",
        discount: 8,
    },
    {
        id: 48,
        name: "Organic Dates",
        category: "Fruits",
        price: 200,
        description: "Premium, organic dried dates",
        image: img,
        brand: "DateNectar",
        type: "Medjool Dates",
        weight: "500g",
        discount: 15,
    },
    {
        id: 49,
        name: "Country Chicken Eggs",
        category: "Farm Products",
        price: 80,
        description: "Organic eggs from country chicken",
        image: img,
        brand: "RuralRoost",
        type: "Free-Range Country Eggs",
        weight: "1 Dozen",
        discount: 10,
    },
    {
        id: 50,
        name: "Raw Sugar",
        category: "Farm Products",
        price: 90,
        description: "Unrefined, organic raw sugar",
        image: img,
        brand: "SweetEarth",
        type: "Organic Cane Sugar",
        weight: "1 kg",
        discount: 12,
    },
];

export const TRENDING = [
    {
        id: 41,
        name: "Sprouted Moong",
        category: "Pulses",
        price: 50,
        description: "Fresh, organic sprouted moong",
        image: img,
        brand: "SproutWell",
        type: "Green Gram Sprouts",
        weight: "250g",
        discount: 12,
    },
    {
        id: 42,
        name: "Green Peas",
        category: "Vegetables",
        price: 40,
        description: "Farm-fresh, sweet green peas",
        image: img,
        brand: "FreshFields",
        type: "Sweet Green Peas",
        weight: "500g",
        discount: 8,
    },
    {
        id: 43,
        name: "Seasonal Mixed Vegetables",
        category: "Vegetables",
        price: 80,
        description: "Assorted fresh vegetables of the season",
        image: img,
        brand: "HarvestMix",
        type: "Seasonal Vegetable Blend",
        weight: "1 kg",
        discount: 15,
    },
    {
        id: 44,
        name: "Dried Curry Powder",
        category: "Spices",
        price: 90,
        description: "Homemade, aromatic curry powder blend",
        image: img,
        brand: "SpiceSaga",
        type: "Traditional Curry Powder",
        weight: "100g",
        discount: 10,
    },
    {
        id: 45,
        name: "Black Pepper Powder",
        category: "Spices",
        price: 100,
        description: "Freshly ground, premium black pepper",
        image: img,
        brand: "PepperKing",
        type: "Tellicherry Black Pepper",
        weight: "100g",
        discount: 12,
    },
    {
        id: 46,
        name: "Groundnut Oil",
        category: "Cooking Oils",
        price: 180,
        description: "Cold-pressed, pure groundnut oil",
        image: img,
        brand: "OilMaster",
        type: "Groundnut Oil",
        weight: "1 Liter",
        discount: 10,
    },
    {
        id: 47,
        name: "Sunflower Oil",
        category: "Cooking Oils",
        price: 160,
        description: "Refined, healthy sunflower oil",
        image: img,
        brand: "SunnyPress",
        type: "Refined Sunflower Oil",
        weight: "1 Liter",
        discount: 8,
    },
    {
        id: 48,
        name: "Organic Dates",
        category: "Fruits",
        price: 200,
        description: "Premium, organic dried dates",
        image: img,
        brand: "DateNectar",
        type: "Medjool Dates",
        weight: "500g",
        discount: 15,
    },
    {
        id: 49,
        name: "Country Chicken Eggs",
        category: "Farm Products",
        price: 80,
        description: "Organic eggs from country chicken",
        image: img,
        brand: "RuralRoost",
        type: "Free-Range Country Eggs",
        weight: "1 Dozen",
        discount: 10,
    },
    {
        id: 50,
        name: "Raw Sugar",
        category: "Farm Products",
        price: 90,
        description: "Unrefined, organic raw sugar",
        image: img,
        brand: "SweetEarth",
        type: "Organic Cane Sugar",
        weight: "1 kg",
        discount: 12,
    },
];

export const BESTSELLER = [
    {
        id: 31,
        name: "Fresh Coriander Leaves",
        category: "Herbs",
        price: 15,
        description: "Aromatic, fresh coriander bunch",
        image: img,
        brand: "HerbHarvest",
        type: "Organic Coriander",
        weight: "100g",
        discount: 10,
    },
    {
        id: 32,
        name: "Mint Leaves",
        category: "Herbs",
        price: 20,
        description: "Fresh, fragrant mint leaves",
        image: img,
        brand: "LeafyFresh",
        type: "Garden Mint",
        weight: "100g",
        discount: 12,
    },
    {
        id: 33,
        name: "Curry Leaves",
        category: "Herbs",
        price: 15,
        description: "Freshly picked curry leaves",
        image: img,
        brand: "AromaGreen",
        type: "Fresh Curry Leaves",
        weight: "50g",
        discount: 8,
    },
    {
        id: 34,
        name: "Ginger",
        category: "Herbs",
        price: 40,
        description: "Fresh, organic ginger root",
        image: img,
        brand: "RootSpice",
        type: "Organic Ginger",
        weight: "250g",
        discount: 10,
    },
    {
        id: 35,
        name: "Garlic",
        category: "Herbs",
        price: 50,
        description: "Fresh, organic garlic bulbs",
        image: img,
        brand: "AllianceFarms",
        type: "White Garlic",
        weight: "250g",
        discount: 12,
    },
    {
        id: 36,
        name: "A2 Cow Milk",
        category: "Dairy",
        price: 70,
        description: "Pure A2 milk from indigenous cow breeds",
        image: img,
        brand: "PureOmega",
        type: "A2 Jersey Cow Milk",
        weight: "1 Liter",
        discount: 15,
    },
    {
        id: 37,
        name: "Homemade Butter",
        category: "Dairy",
        price: 100,
        description: "Traditional hand-churned butter",
        image: img,
        brand: "CreamCraft",
        type: "Cultured Butter",
        weight: "250g",
        discount: 10,
    },
    {
        id: 38,
        name: "Cottage Cheese",
        category: "Dairy",
        price: 180,
        description: "Fresh, soft cottage cheese",
        image: img,
        brand: "CheeseHub",
        type: "Paneer Style Cottage Cheese",
        weight: "250g",
        discount: 12,
    },
    {
        id: 39,
        name: "Pearl Millet Flour",
        category: "Grains",
        price: 60,
        description: "Organic bajra (pearl millet) flour",
        image: img,
        brand: "MilletMaster",
        type: "Bajra Atta",
        weight: "1 kg",
        discount: 8,
    },

    {
        id: 40,
        name: "Finger Millet Flour",
        category: "Grains",
        price: 70,
        description: "Nutritious ragi (finger millet) flour",
        image: img,
        brand: "NutriGrain",
        type: "Ragi Flour",
        weight: "1 kg",
        discount: 10,
    },
];
